FROM python:3.11-slim

WORKDIR /app

COPY pyproject.toml .
COPY uv.lock .

RUN pip install uv && uv pip install --system .

COPY . .

EXPOSE 8501

CMD ["python", "-m", "streamlit", "run", "streamlit_app/app.py", "--server.address=0.0.0.0"]